kind: pipeline
name: default


steps:
  - name: build-push
    image: plugins/docker
    settings:
      username: 
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: nishanthkp/node-app
      dockerfile: ./bulletin-board-app/Dockerfile
