kind: pipeline
name: default

steps:

- name: build
  image: node:current-slim
  commands:
  - npm install

- name: publish
  image: plugins/docker
  settings:
    repo: nishanthkp/node-app
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
