kind: pipeline
name: default

steps:
- name: build-push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - sleep 5 ## give docker enough time to start
#  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build --tag bulletinboard:1.0 .
  - docker push nishanthkp/bulletinboard:1.0
